### ISSUE TITLE
Regex RangeError for large sourcemaps

### ISSUE THREAD

**Issue by tanem** [evanw/node-source-map-support#93]
Hi. We're using [webpack](https://github.com/webpack)'s `devtool: #cheap-module-inline-source-map` option to add an inline base64 encoded source map to the bottom of our main app file. There's a decent amount of code there, so the sourcemap is a pretty gigantic string.

We ended up seeing the following error in the console:

```
RangeError: Maximum call stack size exceeded
    at RegExp.exec (native)
```

Related to [this regex](https://github.com/evanw/node-source-map-support/blob/master/source-map-support.js#L88):

``` js
var re = /(?:\/\/[@#][ \t]+sourceMappingURL=([^\s'"]+?)[ \t]*$)|(?:\/\*[@#][ \t]+sourceMappingURL=([^\*]+?)[ \t]*(?:\*\/)[ \t]*$)/mg;
```

Changing one character in the regex fixes the issue (`...[^\s'"]+?...` to `...[^\s'"]*?...`):

``` js
var re = /(?:\/\/[@#][ \t]+sourceMappingURL=([^\s'"]*?)[ \t]*$)|(?:\/\*[@#][ \t]+sourceMappingURL=([^\*]+?)[ \t]*(?:\*\/)[ \t]*$)/mg;
```

I haven't been able to figure out why that is yet though (e.g. I don't think there's any catastrophic backtracking going on in the original version?) :confused:

Just wondering if anyone else can shed some light on this? Cheers. (PS this change also works for the version currently published to npm).

**Comment by tanem** [comment]
Whoops, just realised this will probably be fixed by #86. Will check tomorrow.

**Comment by SkeLLLa** [comment]
This issue is still present. Are there any plans for fixing this?

Here's more detailed stacktrace, if it helps:
```
"RangeError: Maximum call stack size exceeded"
  "at RegExp.exec (<anonymous>)",
  "at RegExp.[Symbol.match] (native)",
  "at String.match (native)",
  "at urlParse (/myproject/node_modules/source-map-support/node_modules/source-map/lib/util.js:33:20)",
  "at normalize (/myproject/node_modules/source-map-support/node_modules/source-map/lib/util.js:82:13)",
  "at Object.join (/myproject/node_modules/source-map-support/node_modules/source-map/lib/util.js:174:7)",
  "at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/myproject/node_modules/source-map-support/node_modules/source-map/lib/source-map-consumer.js:621:27)",
  "at mapSourcePosition (/myproject/node_modules/source-map-support/source-map-support.js:195:42)"
```

**Comment by telb99** [comment]
This is still a problem with Angular 7 unit tests, which uses jasmine, karma, and webpack and creates very large bundles, on a small project, the bundle for vendor.js is over 17MB.

**Comment by darrengriffinhut42** [comment]
I agree with @telb99. This i still an issue in Angular 8 and needs fixing. @LinusU, please resolve.

**Comment by LinusU** [comment]
Happy to receive a PR for this 🙌

**Comment by darrengriffinhut42** [comment]
@evanw

**Comment by LinusU** [comment]
This should be fixed in version `0.5.13`, please report back if the issue persists!

**Comment by leontastic** [comment]
Just checking in to report that this issue still occurs with the new RegExp in very obscure scenarios. In the case I encountered, it was caused by [this line in the emotion/react repo's `createEmotionProps` function](https://github.com/emotion-js/emotion/blob/1135f8e/packages/react/src/emotion-element.js#L50) that uses `new Error().stack` to update component labels while performing SSR builds with ts-node and next.js.

Interestingly, I was able to intercept the specific file data that caused the error by using local builds of `ts-node` and a local build of the fork of this repo `@cspotcode/source-map-support` that `ts-node` uses, and was not able to reproduce the `RangeError` with this regex independently with just Node.js.

However, overriding `Error.prepareStackTrace` to skip `source-map-support`'s sourcemap transformation logic for stack traces demanded by `createEmotionProps` reliably resolves the error for me:

```ts
if (Error.prepareStackTrace) {
  const originalPrepareStackTrace = Error.prepareStackTrace;
  Error.prepareStackTrace = function (error, trace) {
    if (error.stack?.includes('createEmotionProps')) {
      return error.stack;
    }
    return originalPrepareStackTrace(error, trace);
  };
}
```

Based on [this V8 bug](https://bugs.chromium.org/p/v8/issues/detail?id=3878) I think `RegExp.exec` only throws `RangeError: Maximum call stack size exceeded` when backtracking often over large strings, so I think the current `RegExp` may still be too greedy for certain large inputs.
